parameters:
    umbrella.afct.param.secret: "%env(AFCT_SECRET)%"
    umbrella.afct.param.public: "%env(AFCT_PUBLIC)%"
    umbrella.afct.param.private: "%env(AFCT_PRIVATE)%"


services:
    _defaults:
        autowire: false      # Automatically injects dependencies in your services.
        autoconfigure: false # Automatically registers your services as commands, event subscribers, etc.
        public: true         # this makes public all the services defined in this file


    umbrella.afct.service:
        class: Umbrella\AFCTokenBundle\Service\TokenService
        arguments: []

    umbrella.afct.serializer:
        class: Umbrella\AFCTokenBundle\Service\TokenSerializerService
        arguments: ["%umbrella.afct.param.secret%", "%umbrella.afct.param.private%"]

    umbrella.afct.deserializer:
        class: Umbrella\AFCTokenBundle\Service\TokenDeserializerService
        arguments: ["%umbrella.afct.param.secret%", "%umbrella.afct.param.public%"]