parameters:
    aimchat.afct.param.secret: "%env(AFCT_SECRET)%"
    aimchat.afct.param.public_file: "%env(AFCT_PUBLIC_PATH)%"
    aimchat.afct.param.private_file: "%env(AFCT_PRIVATE_PATH)%"


services:
    _defaults:
        autowire: false      # Automatically injects dependencies in your services.
        autoconfigure: false # Automatically registers your services as commands, event subscribers, etc.
        public: true         # this makes public all the services defined in this file


    aimchat.afct.service:
        class: Aimchat\AFCTokenBundle\Service\TokenService
        arguments: []




    aimchat.afct.key_public.file:
        class: Aimchat\AFCTokenBundle\Service\CryptKey\FileKey
        arguments: ["%aimchat.afct.param.public_file%"]

    aimchat.afct.key_private.file:
        class: Aimchat\AFCTokenBundle\Service\CryptKey\FileKey
        arguments: ["%aimchat.afct.param.private_file%"]




    aimchat.afct.serializer:
        class: Aimchat\AFCTokenBundle\Service\TokenSerializerService
        arguments: ["%aimchat.afct.param.secret%", "@aimchat.afct.key_private.file"]

    aimchat.afct.deserializer:
        class: Aimchat\AFCTokenBundle\Service\TokenDeserializerService
        arguments: ["%aimchat.afct.param.secret%", "@aimchat.afct.key_public.file"]